In [4]:
import torch

In [7]:
x = torch.ones(5)
y = torch.zeros(3)
y

tensor([0., 0., 0.])

In [16]:
w = torch.randn(5,3,requires_grad=True)
b = torch.randn(3,requires_grad=True)
z = torch.matmul(x,w)+b

In [24]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [25]:
loss

tensor(2.0955, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [19]:
loss.backward()

In [22]:
w

tensor([[ 0.2294, -0.1087, -0.8417],
        [ 0.8573,  0.2380,  0.1707],
        [ 1.5696,  0.6127,  0.3308],
        [ 2.2440, -1.1118, -0.2153],
        [ 0.1637, -1.0000,  0.0079]], requires_grad=True)

In [23]:
w.grad

tensor([[0.3272, 0.1954, 0.2519],
        [0.3272, 0.1954, 0.2519],
        [0.3272, 0.1954, 0.2519],
        [0.3272, 0.1954, 0.2519],
        [0.3272, 0.1954, 0.2519]])

In [26]:
b

tensor([-1.0877,  1.7181,  1.6769], requires_grad=True)

In [28]:
b.grad

tensor([0.3272, 0.1954, 0.2519])

In [29]:
inp = torch.eye(5, requires_grad=True)
inp

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)

In [30]:
out = (inp + 1).pow(2)
out

tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)