In [1]:
# UCI German Credit 
import torch
import torch.nn as nn
import numpy as np


In [2]:
data=np.loadtxt("german.data-numeric")


In [3]:
n,l = data.shape

In [4]:
data[0]

array([ 1.,  6.,  4., 12.,  5.,  5.,  3.,  4.,  1., 67.,  3.,  2.,  1.,
        2.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.])

In [5]:
data[1]

array([ 2., 48.,  2., 60.,  1.,  3.,  2.,  2.,  1., 22.,  3.,  1.,  1.,
        1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  2.])

In [6]:
x = data[:,:-1]
y = data[:,-1]
mean = x.mean(axis = 0)
std = x.std(axis=0)
x_norm = (x-mean)/std
data_norm = data.copy()
data_norm[:,:-1] = x_norm

In [7]:
np.random.shuffle(data_norm)

In [8]:
data_norm[:,-1]

array([1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1.,
       1., 2., 2., 1., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.,
       2., 1., 1., 1., 1., 2., 2., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 2., 1.,
       1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2.,
       1., 2., 1., 2., 2., 2., 2., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1.,
       1., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 2.,
       2., 1., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.,
       2., 1., 1., 2., 2., 1., 1., 1., 1., 2., 1., 2., 2., 1., 1., 2., 2.,
       1., 1., 1., 1., 1., 2., 1., 2., 1., 2., 1., 2., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1., 2., 2.,
       1., 2., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1.,
       2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1.,
       1., 1., 1., 1., 1.

In [9]:
train_data = data_norm[:900,:-1]
train_lab = data_norm[:900,-1]-1
test_data = data_norm[900:,:-1]
test_lab = data_norm[900:,-1]-1

In [10]:
class LR(nn.Module):
    def __init__(self):
        super(LR,self).__init__()
        self.fc = nn.Linear(24,2)
    def forward(self,x):
        out = self.fc(x)
        out = torch.sigmoid(out)
        return out

In [11]:
def test(pred,lab):
    t = pred.max(-1)[1] == lab
    return torch.mean(t.float())

In [12]:
net =LR()
criterion = nn.CrossEntropyLoss()
optim = torch.optim.Adam(net.parameters())
epochs = 1000

In [13]:
for i in range(epochs):
    net.train()
    x=torch.from_numpy(train_data).float()
    y=torch.from_numpy(train_lab).long()
    y_hat = net(x)
    loss=criterion(y_hat,y)
    optim.zero_grad()
    loss.backward()
    optim.step()
    if (i+1)%100 == 0:
        net.eval()
        test_in = torch.from_numpy(test_data).float()
        test_l = torch.from_numpy(test_lab).long()
        test_out = net(test_in)
        accu = test(test_out,test_l)
        print("Epoch:{},Loss:{:.4f},Accuracy：{:.2f}".format(i+1,loss.item(),accu))

Epoch:100,Loss:0.6491,Accuracy：0.66
Epoch:200,Loss:0.6180,Accuracy：0.74
Epoch:300,Loss:0.5991,Accuracy：0.74
Epoch:400,Loss:0.5865,Accuracy：0.77
Epoch:500,Loss:0.5774,Accuracy：0.78
Epoch:600,Loss:0.5703,Accuracy：0.79
Epoch:700,Loss:0.5645,Accuracy：0.79
Epoch:800,Loss:0.5596,Accuracy：0.80
Epoch:900,Loss:0.5555,Accuracy：0.80
Epoch:1000,Loss:0.5519,Accuracy：0.79
